---
# tasks file for systemupdates

- name: "Gather facts"
  ansible.builtin.setup:

# Debian/Ubuntu systems
- name: Manage Debian family updates
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  block:
    - name: DEB - Update apt packages
      ansible.builtin.apt:
        upgrade: "{{ systemupdates_upgrade_type | default('dist') }}"
        update_cache: true
        cache_valid_time: "{{ systemupdates_cache_valid_time | default(3600) }}"
        only_upgrade: "{{ systemupdates_only_upgrade | default(false) }}"
        autoclean: "{{ systemupdates_autoclean | default(true) }}"
      register: apt_update_status

    - name: DEB - Run autoremove for apt
      ansible.builtin.apt:
        autoremove: true
      when:
        - apt_update_status.changed
        - systemupdates_autoremove | default(true)
  rescue:
    - name: DEB - Log Debian family update failure
      ansible.builtin.debug:
        msg: "Failed to update Debian system: {{ ansible_failed_task.name }}"

# RedHat/CentOS/Fedora systems
- name: Manage RedHat family updates
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  block:
    - name: RHEL - Update dnf packages  # noqa: package-latest
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
        security: "{{ systemupdates_security_only | default(false) }}"
        bugfix: "{{ systemupdates_bugfix | default(true) }}"
      register: dnf_update_status

    - name: RHEL - Run autoremove for dnf
      ansible.builtin.dnf:
        autoremove: true
      when:
        - dnf_update_status.changed
        - systemupdates_autoremove | default(true)
  rescue:
    - name: RHEL - Log RedHat family update failure
      ansible.builtin.debug:
        msg: "Failed to update RedHat system: {{ ansible_failed_task.name }}"
