---
# tasks file for systemupdates

- name: "Ensure role is run serially to protect clustered services"
  ansible.builtin.fail:
    msg: |
      The 'systemupdates' role is configured to enforce serial execution
      to prevent simultaneous reboots in a cluster.
      This play is attempting to run on {{ ansible_play_batch | length }} host(s)
      concurrently in this batch: {{ ansible_play_batch }}.
      Please set 'serial: 1' in your playbook for the play targeting these hosts.
      To disable this check (not recommended for quorum-based clusters),
      set 'systemupdates_enforce_serial_execution: false' when calling the role.
  when:
    - systemupdates_enforce_serial_execution | default(true)
    - (ansible_play_batch | length) > 1

- name: "Gather facts if not already gathered"
  ansible.builtin.setup:
  when: ansible_facts.os_family is not defined

- name: Initialize update status facts
  ansible.builtin.set_fact:
    apt_update_status:
      changed: false
    dnf_update_status:
      changed: false

- name: Manage Debian family updates
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  block:
    - name: DEB - Update apt packages, excluding MariaDB on Galera hosts
      ansible.builtin.apt:
        upgrade: "{{ systemupdates_upgrade_type | default('dist') }}"
        update_cache: true
        cache_valid_time: "{{ systemupdates_cache_valid_time | default(3600) }}"
        only_upgrade: "{{ systemupdates_only_upgrade | default(false) }}"
        autoclean: "{{ systemupdates_autoclean | default(true) }}"
        # The 'name' parameter with '*' is not compatible with the 'upgrade' parameter.
        # The most flexible way is to manage the Galera upgrade separately.
      when: "'db' not in inventory_hostname"
      register: apt_update_status
      notify: "Check if reboot is required"

    - name: DEB - Include MariaDB Galera upgrade tasks
      when: "'db' in inventory_hostname and 'mariadb_upgrade' in ansible_run_tags"
      ansible.builtin.include_tasks: mariadb_upgrade.yml
  rescue:
    - name: DEB - Log Debian family update failure
      ansible.builtin.debug:
        msg: "Failed to update Debian system: {{ ansible_failed_task.name }}"

- name: Manage RedHat family updates
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  block:
    - name: RHEL - Ensure dnf-utils is installed (for needs-restarting)
      ansible.builtin.dnf:
        name: dnf-utils
        state: present

    - name: RHEL - Update dnf packages
      ansible.builtin.dnf:
        name: "*"
        state: latest  # noqa package-latest
        update_cache: true
        security: "{{ systemupdates_security_only | default(false) }}"
        bugfix: "{{ systemupdates_bugfix | default(true) }}"
      when: "'db' not in inventory_hostname"
      register: dnf_update_status
      notify: "Check if reboot is required"

    - name: RHEL - Include MariaDB Galera upgrade tasks
      when: "'db' in inventory_hostname and 'mariadb_upgrade' in ansible_run_tags"
      ansible.builtin.include_tasks: mariadb_upgrade.yml
  rescue:
    - name: RHEL - Log RedHat family update failure
      ansible.builtin.debug:
        msg: "Failed to update RedHat system: {{ ansible_failed_task.name }}"

- name: Run autoremove for the relevant package manager
  ansible.builtin.package:
    autoremove: true
  when:
    - systemupdates_autoremove | default(true)
    - apt_update_status.changed or dnf_update_status.changed
  become: true
