---
# handlers file for systemupdates

- name: Check and notify for reboot
  listen: "Check if reboot is required"
  block:
    - name: Check for reboot required file (Debian)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file_deb
      when: ansible_facts['os_family'] == 'Debian'

    - name: Check if reboot is required (RedHat)
      ansible.builtin.command: needs-restarting -r
      register: reboot_required_cmd_rhel
      # Exit code 1 means reboot is required, 0 means it is not. Other codes are errors.
      failed_when: reboot_required_cmd_rhel.rc not in [0, 1]
      changed_when: false
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Set reboot required fact
      ansible.builtin.set_fact:
        reboot_is_required: >-
          (ansible_facts['os_family'] == 'Debian' and reboot_required_file_deb.stat.exists) or
          (ansible_facts['os_family'] == 'RedHat' and reboot_required_cmd_rhel.rc == 1)

    - name: Notify reboot if required
      ansible.builtin.debug:
        msg: "A system reboot is required due to recent updates."
      when: reboot_is_required
