---
# handlers file for systemupdates

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_facts['os_family'] == 'Debian'

- name: Notify reboot if required
  ansible.builtin.meta: flush_handlers
  when:
    - ansible_facts['os_family'] == 'Debian'
    - reboot_required_file.stat.exists

- name: Notify reboot
  ansible.builtin.debug:
    msg: "A system reboot is required due to recent updates."
  when: reboot_required_file.stat.exists
