---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
lint: |
  set -e
  ansible-lint
platforms:
  - name: instance
    image: debian:12
    pre_build_image: false
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      local_tmp: /tmp
  inventory:
    host_vars:
      instance:
        ansible_connection: local
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_ROLES_PATH: ../../..
verifier:
  name: ansible
